### ISSUE TITLE
Task: make HTML more organized: Add an aside (except index)

### ISSUE THREAD

**Issue by alexiskrueger5752** [potato-brain/IT115-G3-A5#16]
Put the photo and figcaption in an aside for all pages (except index)

**Comment by alexiskrueger5752** [comment]
- [x] Create aside and style it accordingly
- [x] Put paragraph in aside

**Comment by YA-IT115** [comment]
In case needed, here is more information about HTML <aside> Tag https://www.w3schools.com/TAGS/tag_aside.asp
