### ISSUE TITLE
Add workflow to Sprint 4 project

### ISSUE THREAD

**Issue by potato-brain** [potato-brain/IT115-G3-A5#20]
# add operating workflow to the sprint 4 kanban

**Comment by Dhr0nCrash** [comment]
@potato-brain Ryan and @YA-IT115 Yaser, I have added a new workflow to sprint four, but i am not sure if I placed the .yml file in the right spot. check it out?
https://github.com/potato-brain/IT115-G3-A5/actions/runs/11931871192

**Comment by YA-IT115** [comment]
- [x] Add a Kanban workflow .yml file to Sprint 4.
