### ISSUE TITLE
Add more photos to each page

### ISSUE THREAD

**Issue by potato-brain** [potato-brain/IT115-G3-A5#4]

**Comment by Dhr0nCrash** [comment]
![cedar](https://github.com/user-attachments/assets/fec4f74e-6b18-4586-a18c-a49f6f8d510f)
![item1pic_1](https://github.com/user-attachments/assets/1563fe64-a7cf-41ba-9abf-aaf8280addc5)
![pine](https://github.com/user-attachments/assets/3efea646-30ec-4b0d-ba9d-8b4869c76645)
